### ISSUE TITLE
Installation troubleshoot : Ubuntu pre-requirements

### ISSUE THREAD

**Issue by answerquest** [atlasr-org/atlasr#12]
Hi, can we make a list of all the programs required to be installed before the just `just` command, in Ubuntu? 

- Just : binary has to be download from [their releases](https://github.com/casey/just/releases), and copied to `/home/[user]/.local/bin` so that "just" can be run from command line.
- cargo : this needed to be installed, first script errored out for it. `sudo apt install cargo`
- now it's stuck here: `/usr/bin/ld: cannot find -lsqlite3` . I have sqlite3 installed already, so am stuck.

**Comment by answerquest** [comment]
I'm on Lubuntu 18.04 64-bit OS by the way.

**Comment by answerquest** [comment]
Sorry, here's the `just` error line:
`error: Recipe `install-api-tile` failed on line 94 with exit code 101`
which traces to:  
```
# Install the tile API.
install-api-tile:
	cd source/api/tile && \
		SERVER_ADDRESS={{server_address}} \
		TILE_API_ADDRESS={{tile_api_address}} \
		cargo build --release
```

**Comment by Hywan** [comment]
Hello,

Yes, I can do that :-).
The error about sqlite3 comes from [Diesel](http://diesel.rs/), check with them or in their repositories.

**Comment by johanricher** [comment]
@answerquest I passed this error by installing lua5.3 and lua5.3-dev (with apt), then lsqlite3 and libsqlite3-dev with Luarocks. You also need Rust (make sure you have the latest version) with cargo installed, as well as Elm. I installed just with cargo. 

On my end, after a lot of trial and errors, I'm now stuck, similingy very close to the goal while doing `just install-client-application`, precisely with uglifyjs which throws this error:
```
module.js:550
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/nodejs/uglify-js/bin/uglifyjs:8:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

Don't know if I need yargs, if I need to install it with npm or what. What are the requirements related to Javascript?

Other remarks: Documentation is definitely lacking. Also, "just open" shouldn't download `planet-latest_geonames.tsv.gz` if it's already present. It's a big file!

(Ubuntu 18.10 64 bit)

**Comment by answerquest** [comment]
Hey @johanricher , nice seeing you here. I think I'll wait this one out till someone reports a successful run.

**Comment by Hywan** [comment]
@answerquest @johanricher Do I prepare some tea :-)?
